branch-defaults:
  main:
    environment: astro-okta-prod
    group_suffix: null
deploy:
  artifact: .elasticbeanstalk/app_versions/app.zip
global:
  application_name: astro-okta-app
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: us-gov-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
